Added endpoint for JWT creation
food-manager/backend pull request #30
Opened 2022-07-12 07:42 UTC by mperovicmrsovic

Added endpoint for jwt creation. Work in progress for #1.
Related with pr #29.

In this commit I created endpoint for jwt token creation ( api/users/auth ) .
User Admin is set to create on applications start, for now.
If credentials that user provides during login are wrong I just put to throw new runtime exception with message "Wrong credentials". It should be changed after we add global exception handling.

2022-07-12 13:29 UTC, d-vucetic requested changes

2022-07-12 13:29 UTC, d-vucetic commented on src/main/java/com/g1dra/foodmanager/FoodManagerApplication.java
> +    }
Extract to separate package, lets say we name it seeders. Then there we can have. InitSeederClass

2022-07-12 13:29 UTC, d-vucetic commented on src/main/java/com/g1dra/foodmanager/config/JwtRequest.java
> +public class JwtRequest {
I'm not sure about name of this class. We name is describing response that will get(a jwt). So name of this class should be LoginRequest or similar.

2022-07-12 13:34 UTC, d-vucetic commented
Also pls add test to check if jwt is created. Good method to use when writing tests is: **[Given-When-Then](https://en.wikipedia.org/wiki/Given-When-Then#:~:text=Given%2DWhen%2DThen%20(GWT,words%20given%2C%20when%20and%20then.)**

- given: we have a request with username and password
- when: we make request on auth endpint
- then: we except a response with JWT token

2022-07-18 08:07 UTC, mperovicmrsovic commented on src/main/java/com/g1dra/foodmanager/FoodManagerApplication.java
> +    }
I added seeder package and class for initial data in commit [38575fb](https://github.com/food-manager/backend/pull/30/commits/38575fbb44fbf707f54c3b572a6472a9f241e706)

2022-07-18 08:22 UTC, mperovicmrsovic commented on src/main/java/com/g1dra/foodmanager/config/JwtRequest.java
> +public class JwtRequest {
Renamed into AuthRequest, commit [1769c0a](https://github.com/food-manager/backend/pull/30/commits/1769c0ad2478c33638272684d0fe7ca666b18dd5)

2022-07-19 00:44 UTC, d-vucetic commented
Tests required now..

2022-07-22 12:51 UTC, d-vucetic approved these changes

2022-07-22 12:51 UTC, merged